/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : -- Unnamed --
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_LISTVIEW                            0
#define GD_BUTTON                              1
#define GD_CHECKBOX                            2
#define GD_INTEGER                             3
#define GD_MX                                  4
#define GD_NUMBER                              5
#define GD_CYCLE                               6
#define GD_PALETTE                             7
#define GD_SCROLLER                            8
#define GD_SCR_NUMBER                          9
#define GD_SLIDER                              10
#define GD_STRING                              11
#define GD_TEXT                                12
#define GD_SL_NUMBER                           13

#define GDX_LISTVIEW                           0
#define GDX_BUTTON                             1
#define GDX_CHECKBOX                           2
#define GDX_INTEGER                            3
#define GDX_MX                                 4
#define GDX_NUMBER                             5
#define GDX_CYCLE                              6
#define GDX_PALETTE                            7
#define GDX_SCROLLER                           8
#define GDX_SCR_NUMBER                         9
#define GDX_SLIDER                             10
#define GDX_STRING                             11
#define GDX_TEXT                               12
#define GDX_SL_NUMBER                          13

#define Project0_CNT 14

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *Project0Wnd;
extern struct Gadget        *Project0GList;
extern struct Menu          *Project0Menus;
extern struct IntuiMessage   Project0Msg;
extern struct TextFont      *Font;
extern struct Gadget        *Project0Gadgets[14];
extern UWORD                 Project0Left;
extern UWORD                 Project0Top;
extern UWORD                 Project0Width;
extern UWORD                 Project0Height;
extern UBYTE                *Project0Wdt;
extern UBYTE                *MX0Labels[];
extern UBYTE                *CYCLE0Labels[];
extern struct MinList        LISTVIEW0List;
extern struct TextAttr       XHelvetica9;
extern struct NewMenu        Project0NewMenu[];
extern UWORD                 Project0GTypes[];
extern struct NewGadget      Project0NGad[];
extern ULONG                 Project0GTags[];

extern int LISTVIEWClicked( void );
extern int BUTTONClicked( void );
extern int CHECKBOXClicked( void );
extern int INTEGERClicked( void );
extern int MXClicked( void );
extern int CYCLEClicked( void );
extern int PALETTEClicked( void );
extern int SCROLLERClicked( void );
extern int SLIDERClicked( void );
extern int STRINGClicked( void );
extern int SL_NUMBERClicked( void );
extern int Project0Item0( void );
extern int Project0Item1( void );
extern int Project0Item2( void );
extern int Project0Item3( void );
extern int Project0Item4( void );
extern int Project0Item5( void );
extern int Project0Item6( void );
extern int Project0Item7( void );
extern int Project0Item8( void );

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int HandleProject0IDCMP( void );
extern int Project0CloseWindow();
extern int OpenProject0Window( void );
extern void CloseProject0Window( void );
